-- ============================================================
-- Data Quality Framework DDL — SHARED FOUNDATION
-- Schema : CMSUNIV_FILELAND_DEV_T  (DEV)
-- DB     : Teradata  (metadata store)
-- ============================================================
-- Run this file FIRST, before rules_engine/ddl.sql and/or sampling/ddl.sql.
-- It creates dq_scope (the project/process dimension every other table
-- joins to) — the one table both frameworks depend on. Everything else in
-- this repo's schema is framework-specific and lives in its own folder:
--   rules_engine/ddl.sql  — dq_rules through dq_notification_routes
--   sampling/ddl.sql      — dq_sampling_config, dq_sample_selections
-- ============================================================
-- NOTE: The metadata store is always Teradata.
-- Source systems (PostgreSQL, SQL Server, file, S3) are configured in
-- config/connections.yaml (source_type, host, port, ...) plus DQ_<NAME>_*
-- environment variables for credentials only — see config/connections.py
-- and db/adapters.py for details. There is deliberately no dq_connections
-- table: connection metadata is non-secret, deployment-time configuration
-- that belongs in a version-controlled file, not a database row.
-- ============================================================
--
-- Design notes on the schema shape below:
--
-- 1. dq_scope(scope_id, project_name, process_name) is a single dimension
--    table. Every table that says "this row belongs to project X, process
--    Y" references this table by scope_id instead of repeating the two
--    VARCHAR columns (dq_rules, dq_run_control, dq_metrics_summary,
--    dq_sampling_config). Resolved via utils/db_helpers.py::get_scope_id()
--    (get-or-create) at write time, or find_scope_id() (lookup-only) at
--    read/filter time.
--
-- 2. dq_rule_execution, dq_exceptions, dq_run_logs, dq_column_profile,
--    and dq_anomaly_log all carry run_id, which already maps 1:1 to a
--    dq_run_control row that has scope_id (and, for dq_rule_execution /
--    dq_exceptions, also run_type/run_mode/batch_id/dataset_id/dates).
--    Repeating project_name/process_name/run_type/run_mode/batch_id/
--    dataset_id/start_date/end_date on every one of those child rows would
--    be pure duplication with no audit-fidelity purpose (dq_run_control's
--    values are set once at run start and never change) — none of it is
--    carried on these five tables; it's read back via a JOIN to
--    dq_run_control on run_id.
--
--    dq_sample_selections carries config_id, which already maps 1:1 to a
--    dq_sampling_config row with scope_id — its own project_name/
--    process_name columns are omitted the same way.
--
--    NOT collapsed this way: dq_rule_execution.rule_code/severity/table_name
--    and dq_exceptions.rule_code/table_name. Those are frozen SNAPSHOTS
--    of what a mutable dq_rules row said AT EXECUTION TIME — dq_rules can
--    be edited later (severity reclassified, table renamed), and a CMS
--    audit record must show what was judged at the time, not what a live
--    join to dq_rules says today. That's a deliberate design constraint,
--    not accidental redundancy — see DESIGN.md.
--
-- 3. dq_exception_dispositions layers case-level disposition on top of an
--    immutable dq_exceptions row without repeating run_id, rule_id,
--    rule_code, project_name, process_name, or primary_key_str — all of
--    which already live on dq_exceptions.exception_id, which is ITSELF
--    immutable, so there is no point-in-time-snapshot argument for
--    repeating them here. It carries just the disposition fields, joined
--    to dq_exceptions by exception_id.
--
-- 4. dq_profile_config, dq_anomaly_config, dq_notification_routes are
--    DELIBERATELY NOT normalized to scope_id. These are low-row-count,
--    NULL-wildcard config tables ("NULL project_name = applies to every
--    project") matched by a most-specific-row-wins rule at read time.
--    They're not high-volume fact tables, so the duplication-avoidance
--    payoff is negligible, and collapsing project_name+process_name into
--    a single scope_id FK would still need to represent three distinct
--    wildcard levels (fully global / project-wide / exact project+
--    process), which only adds indirection to the specificity-matching
--    logic in rules_engine/metrics.py, rules_engine/reporting.py, and
--    rules_engine/profiler.py for no real benefit. Left as plain nullable
--    columns on purpose.
--
-- 5. Every table below is CREATE MULTISET, never SET -- deliberately.
--    A SET table's only behavioral difference is silently discarding an
--    INSERT that exactly duplicates an existing row (every column, not
--    just the PI) instead of erroring or storing it. That's a foot-gun
--    for the log/audit-style tables here (dq_run_logs,
--    dq_anomaly_log, ...) -- a repeated log line or a genuine second
--    identical exception is legitimate data, not noise to swallow
--    silently. And on every table whose PRIMARY INDEX is declared UNIQUE
--    (see note 6), SET buys nothing at all: two rows can't be full
--    duplicates if they already can't share a PI value. MULTISET is the
--    only choice that's both correct and never silently drops a row.
--
-- 6. PRIMARY INDEX is declared UNIQUE PRIMARY INDEX everywhere the PI
--    column(s) are meant to be a one-row-per-key identifier (an IDENTITY
--    surrogate key, or an application-assigned natural key like
--    dq_rules.rule_id / dq_run_control.run_id that every FK in this
--    schema points at) -- this makes Teradata itself reject a duplicate
--    key at INSERT time with a clear error instead of silently allowing
--    a second row that then makes every downstream join/lookup on that
--    key ambiguous. Left as a plain (non-unique) PRIMARY INDEX only where
--    more than one row per PI value is the actual documented grain of
--    the table (dq_run_logs, dq_rule_suppressions,
--    dq_exception_dispositions, dq_sample_selections -- each has its own
--    real single-row identity column elsewhere, usually a
--    GENERATED ALWAYS AS IDENTITY column, and the PI is chosen instead
--    for AMP-distribution locality with how the table is actually
--    queried). dq_metrics_summary is the one exception that looks like
--    it should be a UNIQUE PI but isn't: its real uniqueness key
--    (scope_id, run_type, batch_id, dataset_id, run_month) is wider than
--    the PI chosen for distribution, so uniqueness is enforced by
--    dq_metrics_summary_uix instead -- see that table's comment.
--
--    Secondary (CREATE INDEX) indexes are kept to the minimum that
--    actually matches a real WHERE/JOIN in the Python code -- each one
--    left in place has a comment saying which query it serves. An index
--    that doesn't match any query, or duplicates what the PRIMARY INDEX
--    already gives you for free, is worse than useless: it's maintenance
--    overhead on every INSERT/UPDATE/DELETE with no read ever benefiting.
-- ============================================================

-- ============================================================
-- SHARED FOUNDATION — used by both frameworks below.
--
-- This repo hosts TWO SEPARATE FRAMEWORKS against one metadata store:
--   1. The DQ RULES ENGINE       (rules_engine/)     -- dq_rules through
--      dq_anomaly_log below.
--   2. The SAMPLING FRAMEWORK    (sampling/) -- dq_sampling_config and
--      dq_sample_selections below.
-- Neither framework's Python code imports the other (sampling/ uses
-- rules_engine.executor/rules_engine.rule_sql as a plain library — see
-- sampling/engine.py's module docstring — but rules_engine/ has zero
-- awareness sampling/ exists). The two are independently deployable;
-- dq_scope and the connector layer in db/ (config-driven via
-- config/connections.yaml, not a database table) are the only things
-- they share.
-- ============================================================

-- ── dq_scope: project/process dimension — SHARED ───────────────────────────
-- Every other table that needs to say "this row belongs to project X,
-- process Y" references this table by scope_id instead of repeating the
-- two VARCHAR columns. process_name may be NULL (a scope can represent
-- "project X, no sub-process concept"). Both frameworks use this same
-- table — a sampling config and a rule set for the same project/process
-- resolve to the same scope_id.
CREATE MULTISET TABLE CMSUNIV_FILELAND_DEV_T.dq_scope (
    scope_id      BIGINT GENERATED ALWAYS AS IDENTITY,
    project_name  VARCHAR(100) NOT NULL,
    process_name  VARCHAR(100),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
UNIQUE PRIMARY INDEX (scope_id);

CREATE UNIQUE INDEX dq_scope_lookup_uix (project_name, process_name)
ON CMSUNIV_FILELAND_DEV_T.dq_scope;
